/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_espaceAdmin (void);
GtkWidget* create_gadherent (void);
GtkWidget* create_formulaire_ajout (void);
GtkWidget* create_authentification (void);
GtkWidget* create_afficher_adherent (void);
GtkWidget* create_espaceAdherent (void);
GtkWidget* create_espaceCoach (void);
GtkWidget* create_espaceMedecin (void);
GtkWidget* create_espaceDieteticien (void);
GtkWidget* create_espaceKine (void);
