/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_window1 (void);
GtkWidget* create_admin (void);
GtkWidget* create_medecin (void);
GtkWidget* create_desponibilite (void);
GtkWidget* create_fiche_medicale (void);
GtkWidget* create_sceance (void);
GtkWidget* create_Ajouter_fiche (void);
GtkWidget* create_affichage (void);
GtkWidget* create_rdv (void);
GtkWidget* create_effacer (void);
GtkWidget* create_supprime_desp (void);
GtkWidget* create_modifier (void);
GtkWidget* create_coordonner (void);
GtkWidget* create_modifier_coor (void);
